### ISSUE TITLE
Micro vs. Macro

### ISSUE THREAD

**Issue by adletaw** [SrivastavaLab/bwg_names#10]
Fill in the micro/macro column for all species

[Data here](https://github.com/SrivastavaLab/bwg_names/blob/master/data/macromicro.tsv)

**Comment by adletaw** [comment]
@samundrud How is this going?

**Comment by samundrud** [comment]
@adletaw @aammd Hey Alathea, I talked to Andrew a while ago and we decided that it is best that I wait for the taxonomy to be resolved before I do anything more. Andrew will send me an updated data sheet once this is done (right, Andrew?)

**Comment by adletaw** [comment]
Okay - good to know!

On 04/02/2015 11:58 AM, samundrud wrote:
>
> @adletaw <https://github.com/adletaw> @aammd 
> <https://github.com/aammd> Hey Alathea, I talked to Andrew a while ago 
> and we decided that it is best that I wait for the taxonomy to be 
> resolved before I do anything more. Andrew will send me an updated 
> data sheet once this is done (right, Andrew?)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SrivastavaLab/bwg_names/issues/10#issuecomment-89009354>.
>

-- 
Alathea D. L.
PhD Candidate, Srivastava Lab
www.zoology.ubc.ca/~srivast

**Comment by aammd** [comment]
UPDATES
this commit (68ca008795a88ea13358b3dd1b62746c59c2277f) introduces a simple script that will label all ostracods, mites and copepods into "micro"

**QUESTION**: what shall we do with flatworms? Are they micro? I think they should be.
