### ISSUE TITLE
Functional Groups

### ISSUE THREAD

**Issue by adletaw** [SrivastavaLab/bwg_names#12]
Set the functional groups for all species.

[Data here](https://github.com/SrivastavaLab/bwg_names/blob/master/data/functional_group_only.tsv)

**Comment by aammd** [comment]
Er, what data exactly do we need for this one, @DEZERALDOlivier & @dsrivast ? 
Specifically, does Olivier need a dataset with the functional traits?  
@adletaw were you also going to work on this one?

**Comment by adletaw** [comment]
I didn't end up with an assignment so I'm happy to help wherever needed!

On 15-03-11 04:14 PM, Andrew MacDonald wrote:
>
> Er, what data exactly do we need for this one, @DEZERALDOlivier 
> <https://github.com/DEZERALDOlivier> & @dsrivast 
> <https://github.com/dsrivast> ?
> Specifically, does Olivier need a dataset with the functional traits?
>
> @adletaw <https://github.com/adletaw> were you also going to work on 
> this one?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SrivastavaLab/bwg_names/issues/12#issuecomment-78393410>.
>

-- 
Alathea D. L.
PhD Candidate, Srivastava Lab
www.zoology.ubc.ca/~srivast

**Comment by DEZERALDOlivier** [comment]
I am ready to work on this one but where is the file I can work on, should we create on for issue #12?

**Comment by DEZERALDOlivier** [comment]
Forget this question I will work on Terrestrial-Aquatic.tsc!

**Comment by DEZERALDOlivier** [comment]
We need to clarify the functional groups of the following invertebrates, here is what I think (from personal observations):
-Tanypodinae spX and Monopelopia => piercer predators
-Orthocladinae, Chironominae => gatherer (they are assigned the filter feeder group in the functional trait file but I think mouth parts make them gatherers instead)
-Ostracods, Elpidium in particular => scrapers

What do you think?

**Comment by aammd** [comment]
That makes sense.  

Up till now, have you been using the functional/fuzzy traits as a guide for filling in species functional groups? 

If we make the changes you suggest to the functional group column, then we should also change the fuzzy traits to match, no?  In that case @dsrivast should coordinate with you. 

In the meantime, you could create a separate dataset, with a row for every organism you want to correct.  keep this data exactly the same as the original (same columns) but replace the old (potentially erroneous) functional group with your suggestion.  Just a suggestion!

**Comment by DEZERALDOlivier** [comment]
Exactly I've been using the functional/fuzzy traits as a guide (Distribution organisms_correct2015 in Dropbox). And question marks in the previous commit correspond to mismatches with the functional trait file! Then I took the liberty to modify some functional group for which I was sure (culicid, bezzia etc...) and then submited a new commit . Therefore, the coordination with @dsrivast should take the previous commit into account, because of the Githubawesomeness we can go back in time right?

**Comment by adletaw** [comment]
Hm, you may need to talk through some of the mismatches with @dsrivast.  Yes, we can go back in time, but probably shouldn't need to if you are confident in your changes.

**Comment by DEZERALDOlivier** [comment]
I hope you guys are not working on this file I am on it!

**Comment by dsrivast** [comment]
Hi Olivier- Functional traits are almost ready, but not quite, I have about a dozen I am still working on - should have this wrapped up with in a week

**Comment by aammd** [comment]
M. Dezerald dealt with this issue (in its current form) in SHA 5f551371
