### ISSUE TITLE
Functional traits

### ISSUE THREAD

**Issue by adletaw** [SrivastavaLab/bwg_names#13]
Fill out the functional traits data for all species.

[Data here](https://github.com/SrivastavaLab/bwg_names/blob/master/data/functionaltraits.tsv)

**Comment by aammd** [comment]
Do we need to wait for this to be completed before beginning on #12 (functional groups) and #11 (predator-prey?)

**Comment by dsrivast** [comment]
Probably, it is getting very close to complete!

**Comment by aammd** [comment]
as far as the dataset [functionaltraits.tsv](https://github.com/SrivastavaLab/bwg_names/blob/4901285622f71b9f59ad79fb9e5d5c7ad8d2100a/data/functionaltraits.tsv) is concerned, this was corrected in daba0b6377985fec6ebe5cd5ef493daf943b5227
