### ISSUE TITLE
Fix nicknames

### ISSUE THREAD

**Issue by adletaw** [SrivastavaLab/bwg_names#16]
- [ ] Add in missing nicknames
- [ ] Fix spelling in any misspelled nicknames

**Comment by adletaw** [comment]
Vinicius found an error in this nickname already:

https://github.com/SrivastavaLab/bwg_names/blob/master/data/taxonomic.tsv#L78
The organism is a Copepoda, not a Coleoptera.

**Comment by aammd** [comment]
How are we going to add in these missing nicknames? we could write a simple function that would use the order names from Vinicius's work. This could be done after the whole dataset is merged back together, since we're merging on the `key` column

I also feel like I need clarification on what nicknames are even for.

**Comment by adletaw** [comment]
I agree that we should add them in once everything has been merged 
together.  In my opinion, the nicknames should be an easy way for people 
to refer to the same organism with confidence.  The internal database 
key is the computer's way of uniquely referring to an organism whereas 
the nickname is our human way to do the same thing.

Maybe someone else knows, have the nicknames already been used in 
analyses?  It's important that we don't lose a nickname even if it turns 
out to be wrong in some way.  If we change a nickname, I think the old 
nickname should still be preserved in that list of names that goes with 
each species.  That way we can always track back to the correct species 
if someone is using an older name.

**Comment by farjalla** [comment]
I would suggest one major strategy: use the highest meaningful taxonomic
unit possible. For exemple, Diptera is not good enough as 95% of what we
pick up is Diptera. Thus, I would use Cullicidae1, Chironomidae2 and so on.
Other Diperta could be classified by Order such as Trichoptera, Odonate,
Hemiptera. Other groups would include higher taxonomic levels such as
Oligochaetas etc. In summary, I would not go deep into Cullicidea taxonomy,
for instance.

Vinicius F Farjalla, Dr.,
Professor Adjunto
Associate Professor
http://www.researcherid.com/rid/G-4945-2010

Depto. Ecologia,  Inst. Biologia, Universidade Federal do Rio de
Janeiro, Rio de Janeiro, RJ, 21941-590, Brazil.
Phone: +55 21 2562 6374

2015-03-24 15:12 GMT-07:00 Alathea <notifications@github.com>:

**Comment by aammd** [comment]
How do we feel about just keeping incorrect ones? I mean if they are only shorthands for a species name, and only within our own working group, then I'd argue it is harmless if we keep calling Apocyclops "Coleoptera.1"

**Comment by nacmarino** [comment]
I think the best deal is not to mess up with the nickname, ever. This is how each taxon is known in each location and each researcher. For instance, I use more the nickname than any other thing when I'm working with the data.

Enviada do meu iPhone

**Comment by adletaw** [comment]
I think I agree with that.  It could be confusing to change them even if 
they are wrong.  It doesn't matter so much since you can look in the 
database to find the actual taxonomic information.

On 03/24/2015 03:58 PM, Nicholas Marino wrote:
> I think the best deal is not to mess up with the nickname, ever. This 
> is how each taxon is known in each location and each researcher. For 
> instance, I use more the nickname than any other thing when I'm 
> working with the data.
>
> Enviada do meu iPhone
>
> > Em 24/03/2015, às 15:52, Vinicius Farjalla 
> <notifications@github.com> escreveu:
> >
> > I would suggest one major strategy: use the highest meaningful taxonomic
> > unit possible. For exemple, Diptera is not good enough as 95% of what we
> > pick up is Diptera. Thus, I would use Cullicidae1, Chironomidae2 and 
> so on.
> > Other Diperta could be classified by Order such as Trichoptera, Odonate,
> > Hemiptera. Other groups would include higher taxonomic levels such as
> > Oligochaetas etc. In summary, I would not go deep into Cullicidea 
> taxonomy,
> > for instance.
> >
> > Vinicius F Farjalla, Dr.,
> > Professor Adjunto
> > Associate Professor
> > http://www.researcherid.com/rid/G-4945-2010
> >
> > Depto. Ecologia, Inst. Biologia, Universidade Federal do Rio de
> > Janeiro, Rio de Janeiro, RJ, 21941-590, Brazil.
> > Phone: +55 21 2562 6374
> >
> > 2015-03-24 15:12 GMT-07:00 Alathea <notifications@github.com>:
> >
> > > I agree that we should add them in once everything has been merged
> > > together. In my opinion, the nicknames should be an easy way for 
> people
> > > to refer to the same organism with confidence. The internal database
> > > key is the computer's way of uniquely referring to an organism whereas
> > > the nickname is our human way to do the same thing.
> > >
> > > Maybe someone else knows, have the nicknames already been used in
> > > analyses? It's important that we don't lose a nickname even if it 
> turns
> > > out to be wrong in some way. If we change a nickname, I think the old
> > > nickname should still be preserved in that list of names that goes 
> with
> > > each species. That way we can always track back to the correct species
> > > if someone is using an older name.
> > >
> > >
> > > On 03/24/2015 03:01 PM, Andrew MacDonald wrote:
> > > >
> > > > How are we going to add in these missing nicknames? we could write a
> > > > simple function that would use the order names from Vinicius's work.
> > > > This could be done after the whole dataset is merged back together,
> > > > since we're merging on the |key| column
> > > >
> > > > I also feel like I need clarification on what nicknames are even 
> for.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > 
> https://github.com/SrivastavaLab/bwg_names/issues/16#issuecomment-85710821
> > > >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/SrivastavaLab/bwg_names/issues/16#issuecomment-85713284>
> > > .
> > >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SrivastavaLab/bwg_names/issues/16#issuecomment-85728517>.
>

-- 
Alathea D. L.
PhD Candidate, Srivastava Lab
www.zoology.ubc.ca/~srivast

**Comment by farjalla** [comment]
Ok, it is an option but there are some misspellings. Those must be
corrected to retrieve the complete information from the dataset.

Vinicius F Farjalla, Dr.,
Professor Adjunto
Associate Professor
http://www.researcherid.com/rid/G-4945-2010

Depto. Ecologia,  Inst. Biologia, Universidade Federal do Rio de
Janeiro, Rio de Janeiro, RJ, 21941-590, Brazil.
Phone: +55 21 2562 6374

2015-03-24 15:58 GMT-07:00 Nicholas Marino <notifications@github.com>:

**Comment by aammd** [comment]
@adletaw just to ping you -- what is our status on this question? (i see you are self-assigned here :stuck_out_tongue_winking_eye: )
@dsrivast what do you think is the best way forward? Should mispelled nicknames be discarded?

**Comment by adletaw** [comment]
Ah.  I haven't started this yet as I was waiting for all of the other 
issues to be completed.  We need to both fix misspelled, and add new 
ones for those missing a nickname.

On 5/12/2015 1:01 PM, Andrew MacDonald wrote:
>
> @adletaw <https://github.com/adletaw> just to ping you -- what is our 
> status on this question? (i see you are self-assigned here 
> :stuck_out_tongue_winking_eye: )
> @dsrivast <https://github.com/dsrivast> what do you think is the best 
> way forward? Should mispelled nicknames be discarded?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SrivastavaLab/bwg_names/issues/16#issuecomment-101404075>.
>

-- 
Alathea D. L.
PhD Candidate, Srivastava Lab
www.zoology.ubc.ca/~srivast

**Comment by dsrivast** [comment]
Hi guys - Nicholas is right here I think. The nicknames should never, ever be altered once assigned, no matter if there are spelling mistakes, extra spaces, etc. For example, there were species that we thought were Diptera but that are not, but we need to keep calling them Diptera.43 or whatever just to make sure that our species handle never becomes disassociated with the data....as that is the only function of these nicknames (In fact, I encourage you to call these BWGcodes instead of nicknames, to emphasize that they are not something informal, and to emphasize their function).  If there are spelling mistakes in the actual taxonomic information rather than the BWGcodes, that's a totally different matter, those do need to be fixed. 
@adletaw , @aammd , @farjalla , @nacmarino : Do you agree to change this issue to just missing nicknames/BWGcodes?

**Comment by adletaw** [comment]
Okay, I agree with that.  My only worry is internal inconsistencies in spelling.  For example, If one group of researchers uses Oligochaeta.1 and another uses Oligocheata.1 for the same species.  @farjalla mentioned some misspellings, but is this what you meant?  I looked through our full dataset just now and didn't catch anything like that.

**Comment by nacmarino** [comment]
I agree with Diane. No fixes on the BWGcodes. Besides, this is only a way
to ID which organism is which, and in a publication should be presented as
the original taxonomic name, right?

**Comment by adletaw** [comment]
Nicknames will not be changed.
