### ISSUE TITLE
Add higher levels of taxonomic resolution to the taxonomy table

### ISSUE THREAD

**Issue by adletaw** [SrivastavaLab/bwg_names#17]
Add the higher levels of taxonomic resolution so we can incorporate other kingdoms into the database (bacteria, fungi, etc.)

https://github.com/SrivastavaLab/bwg_names/blob/master/data/taxonomic.tsv

**Comment by farjalla** [comment]
Is it for me? Guess so.
I will add Domain and Kingdom, ok?

Vinicius F Farjalla, Dr.,
Professor Adjunto
Associate Professor
http://www.researcherid.com/rid/G-4945-2010

Depto. Ecologia,  Inst. Biologia, Universidade Federal do Rio de
Janeiro, Rio de Janeiro, RJ, 21941-590, Brazil.
Phone: +55 21 2562 6374

2015-04-02 11:22 GMT-07:00 Alathea <notifications@github.com>:

**Comment by adletaw** [comment]
I assigned it for myself, but you can do it if you want to :)

**Comment by farjalla** [comment]
I will do it as I have to see the quotation marks

Vinicius F Farjalla, Dr.,
Professor Adjunto
Associate Professor
http://www.researcherid.com/rid/G-4945-2010

Depto. Ecologia,  Inst. Biologia, Universidade Federal do Rio de
Janeiro, Rio de Janeiro, RJ, 21941-590, Brazil.
Phone: +55 21 2562 6374

2015-04-02 11:32 GMT-07:00 Alathea <notifications@github.com>:

**Comment by adletaw** [comment]
Okay, I will let you work on those two things.  I'll reassign them to 
you so there is no confusion.

On 04/02/2015 11:35 AM, Vinicius Farjalla wrote:
> I will do it as I have to see the quotation marks
>
> Vinicius F Farjalla, Dr.,
> Professor Adjunto
> Associate Professor
> http://www.researcherid.com/rid/G-4945-2010
>
> Depto. Ecologia, Inst. Biologia, Universidade Federal do Rio de
> Janeiro, Rio de Janeiro, RJ, 21941-590, Brazil.
> Phone: +55 21 2562 6374
>
> 2015-04-02 11:32 GMT-07:00 Alathea <notifications@github.com>:
>
> > I assigned it for myself, but you can do it if you want to :)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/SrivastavaLab/bwg_names/issues/17#issuecomment-89003425>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SrivastavaLab/bwg_names/issues/17#issuecomment-89003966>.
>

-- 
Alathea D. L.
PhD Candidate, Srivastava Lab
www.zoology.ubc.ca/~srivast

**Comment by farjalla** [comment]
close #18

**Comment by dsrivast** [comment]
@farjalla I found a few errors in the taxonomic info in the original data, can you confirm if you have fixed them in the meantime? (1) Tanypodinae is a subfamily, but was erroneously listed as a family for Diptera.424 and Diptera.433  (2) Rumphomyia is in Empididae, but was erroneously put in Culicidae (by the macae crew!).

**Comment by aammd** [comment]
@dsrivast @farjalla I can confirm that the Tanypodinae is OK, and 
_Runchomyia_ is spelt correctly in the **Genus** column of the spreadsheet, but is mispelled as _Rumphomyia_ in the Name column. 
_Runchomyia_ is a Culicid. :sweat_smile:
