### ISSUE TITLE
Remove question marks in taxonomic data

### ISSUE THREAD

**Issue by adletaw** [SrivastavaLab/bwg_names#18]
Some names have question marks.  

For example:
https://github.com/SrivastavaLab/bwg_names/blob/master/data/taxonomic.tsv#L22

**Comment by farjalla** [comment]
hum. I will see it


Vinicius F Farjalla, Dr.,
Professor Adjunto
Associate Professor
http://www.researcherid.com/rid/G-4945-2010

Depto. Ecologia,  Inst. Biologia, Universidade Federal do Rio de
Janeiro, Rio de Janeiro, RJ, 21941-590, Brazil.
Phone: +55 21 2562 6374

2015-04-02 11:32 GMT-07:00 Alathea <notifications@github.com>:

**Comment by farjalla** [comment]
close #18

**Comment by farjalla** [comment]
close #17
