### ISSUE TITLE
Switching to working on the full dataset

### ISSUE THREAD

**Issue by aammd** [SrivastavaLab/bwg_names#19]
Hello @SrivastavaLab/users ,

Excellent work everyone! we have made considerable progress on filling in this dataset.  I have assembled a quick report on the topic (see a preview of the present version [here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SrivastavaLab/bwg_names/master/report/report.html)). For the latest version of the report, go to the /report folder

We are going to switch to editing the full file. This is [data/Distributions_organisms_full.tsv](https://github.com/SrivastavaLab/bwg_names/blob/master/data/Distributions_organisms_full.tsv).  Nicolas, Diane and I have already modified this file (eg 14e80fee). Thus, those smaller sub datasets we started using are _already out of date_. So, don't use them.

Please look at your section of the report. Let me know if I have missed anything, or if there are other checks to include. Better yet edit the original .Rmd file if you have any suggestions!

***SUGGESTION*** let's use this thread to discuss what the next steps are. We have to be careful, because if we are all on the same file we should try hard to avoid conflicts. Here is my suggestion

* discuss here what we need to do next
* open issues for each
* assign them to people
* do them one at a time

Congratulations again everyone! good work

**Comment by adletaw** [comment]
@aammd Thank you for your really great and comprehensive report.  I have opened issues for each of the topics you mentioned therein.  It looks like we need to come to some agreement on what to do for each one before assigning them.

**Comment by aammd** [comment]
Thank you @adletaw, I think we should just discuss each of these things individually :smile_cat:
