### ISSUE TITLE
Adding fuzzy traits

### ISSUE THREAD

**Issue by adletaw** [SrivastavaLab/bwg_names#22]
Some species have no fuzzy trait information even though they are identified to family or lower taxonomic level.  @dsrivast Would it be possible to fill in some of this information for those species?  The details are in [Andrew's report](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SrivastavaLab/bwg_names/master/report/report.html) under `Functional traits`.

**Comment by dsrivast** [comment]
I've been working on solving this. The following species on Andrew's report under functional traits are terrestrial, and so will never have functional traits: Coleoptera.40, .54,.56,.20 and Lepidoptera.1  If you felt inclined, the code could be changed on the report to exclude terrestrials.
The others: I am waiting on a ID confirmation from Macae for the"black headed chironomid", Muscidae will be copied over fro Tachet's traits, and Sarcophadidae requires painful research. Meanwhile, I seem to have jammed up my last commit - "fatal: Unable to create... File exists..Make sure no other git
process is running and remove the file manually to continue."  Remove the file manually from what exactly? Rstudio dialog box? my harddrive? If one of the A team could unstump me, I'd be grateful.
@adletaw, @aammd

**Comment by adletaw** [comment]
@dsrivast Just to confirm, this error occurred while committing, not pushing to Github?  Did the error message name a file like this:

`../.git/index.lock`

With a `.lock` extension?  If so, you can find that referenced file on your computer and delete it.  Your commits should work then.

**Comment by dsrivast** [comment]
Yes, "Unable to create 'C:/Users/Diane/Dropbox/Bwgdb project/bwg_names/.git/index.lock': File exists."
OK I'll try that, thanks

**Comment by adletaw** [comment]
And hopefully you don't have two Git's open somehow.

**Comment by nacmarino** [comment]
Need something from the Macae data?

**Comment by dsrivast** [comment]
Success, thanks @adletaw. Nicholas @nacmarino  I sent you an email about Macae's "black headed chironomid"...I wonder if it is Sciaridae instead...

**Comment by aammd** [comment]
@dsrivast @nacmarino is the controversial Chironomid: [Diptera.54](https://github.com/SrivastavaLab/bwg_names/blob/master/data/09_Distributions_organisms_full.tsv#L239)? If so, can we figure out if it is indeed Sciaridae before we start working on the fuzzy traits?  I couldn't find any history of Diane or Nicolas modifying a chironomid so i don't think that has happened yet

**Comment by dsrivast** [comment]
We successfully concluded that this is Sciaridae, I just never had time to
update the record.
-- 
Diane Srivastava
Professor
Dept of Zoology & Biodiversity Research Centre,
University of British Columbia
6270 University Blvd
Vancouver BC Canada V6T 1Z4
604-822-1350 (no voicemail)

**Comment by adletaw** [comment]
Sciaridae problem moved to #42.  Dealing with the Tachet traits moved to issues: #34, #35, #36, #37, #38
