### ISSUE TITLE
Aquatic terrestrial

### ISSUE THREAD

**Issue by adletaw** [SrivastavaLab/bwg_names#23]
In the aquatic/terrestrial column, some species are marked as "**a**" meaning that the principle researcher has been contacted but has not responded yet.  At some point, we should stop waiting for these responses and mark these as `NA`.

Take a look in [Andrew's report](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SrivastavaLab/bwg_names/master/report/report.html) under `aquatic.terrestrial`.

**Comment by aammd** [comment]
@nacmarino , would you please contact the researchers here again? We are still missing many aquatic/terrestrial values. If we can't fill them in soon (deadline = Next Friday) we'll have to enter them as NA, then (painfully) change them cell by cell in the relational database :cold_sweat: 
cc @dsrivast

**Comment by nacmarino** [comment]
All information filled!

**Comment by adletaw** [comment]
Awesome!!! thanks!
