### ISSUE TITLE
cut up by row into about 9 groups

### ISSUE THREAD

**Issue by aammd** [SrivastavaLab/bwg_names#29]
for fuzzy trait checking

* do they match within a broad taxonomic group
* do they match Tache

Checking against Diane's notes with reference to Kathleen's identification of problems ( in spreadsheet).
Note that our little sub-datasets should be sorted taxonomically.

EDIT: I will cut this into groups for 4 teams of 2 people to work on, + 1 group for me (Alathea).

EDIT: The groups will be:
1. Oligochaeta, Coleoptera, unknown Diptera, Dolichopodidae, Empididae, Ephydridae, Muscidae, Brachycera, Sarcophagidae, Stratiomyidae
2. Syrphidae, Tabanidae, Ceratopogonidae
3. Chironomidae
4. Culicidae
5. Limoniidae, Nematocera, Psychodidae, Tipulidae, Megaloptera, Ephemeroptera, Odonata, Nematoda, Unknown (Alathea will do this one)

**Comment by adletaw** [comment]
I am looking at the annotated `Distributions_organisms_full` file provided by Kathleen and Sadie.  Could you confirm that this interpretation is correct (@dsrivast or @khiggins012)?  
1.  The highlighted rows that are missing several columns at the beginning are Tachet traits found from some external source; these species may or may not be present in our data sets and the rows were inserted.
2.  The highlighted rows with all columns present are species that have been found in our data sets.

**Comment by adletaw** [comment]
I have compiled a list of problem groups.  We need to compress this into 9 sets.

The lowest taxonomic level in common is given.  e.g. `Diptera : Syrphidae` means traits are mismatched at the family level whereas `Diptera: Syrphidae : Eristalis` means traits are mismatched at the genus level

M   = Data mismatched within taxonomic groups
NA = All data NA (research may be needed to fill out these rows)

| Taxonomic Group | Rows Involved | Problem |
|------------------------|--------------------|-------------|
| Oligocheata: Nadidae | 5 | M |
| Coleoptera | 9 | NA |
| Coleoptera: Carabidae | 1 | NA |
| Coleoptera: Curculionidae | 1 | NA |
| Coleoptera: Elateridae | 2 | NA |
| Coleoptera: Hydrophilidae | 11 | M |
| Coleoptera: Polyphaga | 2 | NA |
| Coleoptera: Scirtidae | 5 | M |
| Diptera | 29 | NA |
| Diptera: Dolichopodidae | 5 | M |
| Diptera: Empididae | 9 | M |
| Diptera: Ephydridae | 17 | M |
| Diptera: Muscidae | 3 | NA |
| Diptera: Brachycera | 9 | NA |
| Diptera: Brachycera | 3 | M |
| Diptera: Sarcophagidae | 1 | NA |
| Diptera: Stratiomyidae | 5 | M |
| Diptera: Syrphidae | 11 | M |
| Diptera: Syrphidae : Copestylum | 7 | M |
| Diptera: Syrphidae : Eristalis | 2 | M |
| Diptera: Syrphidae : Meromacrus | 4 | M |
| Diptera: Syrphidae : Eristalinae | 2 | M |
| Diptera: Tabanidae | 13 | M |
| Diptera: Tabanidae: Stibasoma | 2 | M |
| Diptera: Ceratopogonidae | 15 | M |
| Diptera: Ceratopogonidae: Bezzia | 11 | M |
| Diptera: Ceratopogonidae: Culicoides | 3 | M |
| Diptera: Ceratopogonidae: Sphaeromias | 2 | M |
| Diptera: Ceratopogonidae: Atrichopogon | 13 | M |
| Diptera: Ceratopogonidae: Forcipiomyia | 5 | M |
| Diptera: Ceratopogonidae: Forcipiomyiinae | 9 | M |
| Diptera: Ceratopogonidae: Forcipiomyia | 5 | M |
| Diptera: Chironomidae | 29 | M |
| Diptera: Chironomidae: Chironominae | 3 | M |
| Diptera: Chironomidae: Polypedilum | 2 | NA |
| Diptera: Chironomidae: Polypedilum | 10 | M |
| Diptera: Chironomidae: Tanytarsus | 6 | M |
| Diptera: Chironomidae: Limnophyes | 2 | M |
| Diptera: Chironomidae: Metriocnemus | 4 | M |
| Diptera: Chironomidae: Orthocladiinae | 12 | M |
| Diptera: Chironomidae: Phytotelmatocladius | 3 | M |
| Diptera: Chironomidae: Larsia | 6 | M |
| Diptera: Chironomidae: Monopelopia | 3 | M |
| Diptera: Chironomidae: Tanypodinae | 4 | M |
| Diptera: Corethrellidae | 3 | M |
| Diptera: Corethrellidae: Corethrella | 12 | M |
| Diptera: Culicidae | 3 | M |
| Diptera: Culicidae: Anopheles | 5 | M |
| Diptera: Culicidae: Aedes | 3 | M |
| Diptera: Culicidae: Anopheles | 5 | M |
| Diptera: Culicidae: Culex | 46 | M |
| Diptera: Culicidae: Toxorhynchites | 14 | M |
| Diptera: Culicidae: Wyeomyia | 31 | M |
| Diptera: Limoniidae: Limoniinae | 4 | M |
| Diptera: Limoniidae: Trentepohlia | 8 | M |
| Diptera: Nematocera | 1 | NA |
| Diptera: Psychodidae | 18 | M |
| Diptera: Psychodidae: Pericoma | 3 | M |
| Diptera: Psychodidae: Telmatoscopus | 4 | M |
| Diptera: Tipulidae | 14 | M |
| Diptera: Tipulidae: Tipulinae | 2 | M |
| Hemiptera: Veliidae | 1 | NA |
| Lepidoptera | 5 | NA |
| Lepidoptera: Glossata | 1 | NA |
| Lepidoptera: Glossata: Tineidae | 1 | NA |
| Megaloptera | 1 | NA |
| Ephemeroptera | 1 | NA |
| Odonata: Coenogrionidae: Leptagrion | 6 | M |
| Nematoda | 2 | NA |
| Unknown | 3 | NA |

**Comment by dsrivast** [comment]
Yes, this interpretation is correct. Perhaps we should paste the content
of Kathleen's email that I forwarded to you here, as she explains nicely
her highlighting system.

Alathea - I think you have used some R code to generate this "issues"
table (nice job by the way). If so, please add a filter to look only at
species that are aquatic, not terrestrial - that should explain most of
the NA rows.

Remember the two main categories of problems are:
- Species in the same genus or same family differ in their trait codes,
need to return to documentation to ensure not a mistake - fix if is,
involve DS at this step.
- Even if consistent within genus or family, may have deviated from
Tachet's coding. This need some judgement about whether the deviation is
justified, return to documentation, look to see if Tachet's traits are
based on different species than ours, involve DS at this step.

-- 
Diane Srivastava
Professor
Dept of Zoology & Biodiversity Research Centre,
University of British Columbia
6270 University Blvd
Vancouver BC Canada V6T 1Z4
604-822-1350 (no voicemail)

**Comment by adletaw** [comment]
No, I did this by hand :cry: I will go back and take a look at where the terrestrial species are and remove those from the table above.  My main goal was to find out how many problems there are in each taxonomic group so that we can divide the data into 9 sets along taxonomic lines.  The table isn't meant to have any bearing on how those problems are solved - and is probably not even totally accurate.

You are right that we should put those reference guides as well as Kathleen's explanation somewhere.  Maybe we need a different issue, though, to describe those things as well as the problem solving process so that everyone is clear on what they should be doing and when to consult you.

**Comment by adletaw** [comment]
@aammd What should I do about unaffected rows?  Leave them in?  Separate them into their own set?  I suppose this goes back to how you want to deal with merging the data.

**Comment by dsrivast** [comment]
Create a section of all unaffected rows?
-- 
Diane Srivastava
Professor
Dept of Zoology & Biodiversity Research Centre,
University of British Columbia
6270 University Blvd
Vancouver BC Canada V6T 1Z4
604-822-1350 (no voicemail)

**Comment by adletaw** [comment]
I have created a script to split the data set.  This script runs on `09_Distributions_organisms_full.tsv` and splits the data by rows.  Separated files can be regenerated if any changes are made to the data set before editing begins.
