### ISSUE TITLE
Add master script

### ISSUE THREAD

**Issue by adletaw** [SrivastavaLab/bwg_names#30]
Add a master script that runs all of the scripts for merging and preparing the data for upload.

**Comment by aammd** [comment]
Oh i'd be happy to!
:neutral_face: 
wait which scripts would these be

**Comment by adletaw** [comment]
That is the question!  There is one for merging, then one for adding micro macro, then... ?  The problem is I'm not totally sure.  My [renaming columns](https://github.com/SrivastavaLab/bwg_names/blob/master/Rscripts/renaming_columns.R) script takes the `Distributions_correct` file and generates a new `forupload.csv`, so that should probably be the last one.  Alternatively, we could combine everything into a single file.

Why is your happy face not happy though? :confused:

**Comment by aammd** [comment]
Oh yes! that was what i was thinking. I feel like we need to discuss what purpose exactly these scripts serve. 
(related: I love your `renaming_columns.R` script btw, great idea)

Do the scripts: 

1. help us document modifications (not additions) and help us be rigorous about it (ie using `ifelse` rather than search-and-replace in Excel)
2. in addition, help us to reproduce the final data.

Right now we only have 1, not 1 & 2. I would love if that was possible, but we would have needed a different workflow. Because people have been making edits to the dataset itself, we can't "replay" all the R scripts without losing all the work we've done.  Which might be a flaw? Should we try to adopt such a workflow with our next steps?
re: face i was just trying to be cute :carousel_horse:

**Comment by aammd** [comment]
For example, at present if people want to change the data they just edit the most current version of the data. A more reproducible way would be for people to store any edits they have in a small file and then run an R script that would apply those changes to the main data.

For example, if you have to modify 5 fuzzy traits for two species, you write a .csv file with just those two species in the rows (even just the `key` column) and just the variables you want to change in the columns, then that is applied to the main data.

**Comment by adletaw** [comment]
Oh I see.  So there have been direct edits not only to the split up data sets, but also to the remerged data set?  The problem is that there are also modifications being made to the split up datasets (e.g. Nicholas just finished fixing up the aquatic/terrestrial column).  So how do we get back to a merged dataset without undoing any work that was done to the full data?  I know we can't go from raw data directly to clean data, but ideally we would be able to just run the scripts on the split data and reproduce the final merged data.  Is that possible?

**Comment by adletaw** [comment]
For the sake of ease of completing the project, I am okay with direct edits being made to the split-up versions of data sets rather than using R scripts.  It is not ideal because of the possibility that we may change the master raw data and then where would we be?  But that is unlikely to occur and ultimately we are going to generate one data set and then never use these scripts again.

I am less okay with directly modifying `Distributions_organisms_full.tsv` without the use of a script because edits may be made to the split-up files at any time and we need to be able to remerge those without undoing any changes that were made.

**Comment by aammd** [comment]
Ohh so you're saying that in 12cfcec07da0c60ad6d4b53ac36eaba2d665cd31 Nicolas modified the same file on which he made his original changes? Its true, some of the other columns in that dataset might be outdated in the main dataset right now.  Though probably nothing that would prevent a merge with the new versions of the data.

**Comment by adletaw** [comment]
Yes, my preferred workflow is:
1. split data
2. the relevant teams of people edit their data subsets
3. R scripts are used to recombine the split-up data into a final dataset for uploading

**Comment by adletaw** [comment]
Perhaps if this is no longer possible, we can use this workflow for the next split-recombine step on fuzzy traits.

**Comment by adletaw** [comment]
I think the current numbering system solves this problem.

**Comment by aammd** [comment]
Why don't we make a master .R script that just runs all the data-cleaning code in order? It could begin with 
`setwd("Rscripts")`, 
thus combining our separate approaches :joy:

**Comment by adletaw** [comment]
Ah!  That is a good idea.  Then we don't have to run all the numbered ones separately.

**Comment by adletaw** [comment]
It will have to be a sub-master that only goes up to splitting into Tachet traits.  Otherwise, my split script will overwrite the `tachet_...tsv` files and any edits that have been made will be overwritten.  So I suppose we should have one for doing all of the steps up to splitting.  And one for doing all of the steps from recombining on.
