### ISSUE TITLE
upload kathleen's notes on the names

### ISSUE THREAD

**Issue by aammd** [SrivastavaLab/bwg_names#33]
We want to have a central place for reference to all the notes that Kathleen has taken on the problems in the fuzzy traits.

**Comment by adletaw** [comment]
As well as Diane, Regis, Pavel, etc. notes on how the trait values were determined, and a howto including [Diane's guidelines on how to complete the work](https://github.com/SrivastavaLab/bwg_names/issues/29#issuecomment-120504439)
