### ISSUE TITLE
Check Tachet traits for the Chironomidae

### ISSUE THREAD

**Issue by adletaw** [SrivastavaLab/bwg_names#34]
The team working on this data set will check the traits for all Chironomidae.  The data set is [in the data subdirectory of this repository](https://github.com/SrivastavaLab/bwg_names/tree/master/data) and called `tachet_01_chironomidae.tsv`.  Please edit only the values in the Tachet traits columns, using a separate branch.  When you are done, submit a merge request and Diane will check your results before the data sets are merged together.

Please see [the Tachet subdirectory](https://github.com/SrivastavaLab/bwg_names/tree/master/Tachet) for details.  There you will find [Kathleen and Sadie's file highlighting mismatched and missing Tachet traits](https://github.com/SrivastavaLab/bwg_names/blob/master/Tachet/Distributions_organisms_full_SadieKathleen.xlsx) as well as [Diane's file describing how existing Tachet traits were determined](https://github.com/SrivastavaLab/bwg_names/blob/master/Tachet/Traits_All_Sources.doc).  Furthermore, a key for Katheleen and Sadie's file is described in the README for that subdirectory, as well as a description of what to do.

**Comment by aammd** [comment]
Er one sec though, do these sliced-up subsets contain the updated data from Nicolas?

**Comment by dsrivast** [comment]
I have a file with modal trait values to replace the non-integer mean values, for chironomids and ceratopogonids. Please contact me when you need this.

**Comment by adletaw** [comment]
completed with [merge](https://github.com/SrivastavaLab/bwg_names/commit/ba20bffee35cbc7f2cadb20d6872e3721e6b7768)
