### ISSUE TITLE
Check Tachet traits for the Limoniidae et al.

### ISSUE THREAD

**Issue by adletaw** [SrivastavaLab/bwg_names#37]
EDIT: This set will also include the Sciaridae.  Note that the Sciaridae are not currently listed in Kathleen's document, but we are adding a new species so the Tachet traits must be compared (#42).

The team working on this data set will check the traits for all Limoniidae, Psychodidae, Tipulidae, Nematocera (unknown family), Megaloptera, Ephemeroptera, Odonata and Nematoda.  The data set is [in the data subdirectory of this repository](https://github.com/SrivastavaLab/bwg_names/tree/master/data) and called `tachet_04_limoniidae_etal.tsv`.  Please edit only the values in the Tachet traits columns, using a separate branch.  When you are done, submit a merge request and Diane will check your results before the data sets are merged together.

Please see [the Tachet subdirectory](https://github.com/SrivastavaLab/bwg_names/tree/master/Tachet) for details.  There you will find [Kathleen and Sadie's file highlighting mismatched and missing Tachet traits](https://github.com/SrivastavaLab/bwg_names/blob/master/Tachet/Distributions_organisms_full_SadieKathleen.xlsx) as well as [Diane's file describing how existing Tachet traits were determined](https://github.com/SrivastavaLab/bwg_names/blob/master/Tachet/Traits_All_Sources.doc).  Furthermore, a key for Katheleen and Sadie's file is described in the README for that subdirectory, as well as a description of what to do.

**Comment by adletaw** [comment]
@dsrivast Do you have an idea about what to do with species that have only been identified to family or subfamily level but have mismatched traits?  Should the traits all match?  Or may these traits have been observed in the field even if the morphospecies is not further identified?

**Comment by dsrivast** [comment]
body size is generally from field observations, the other traits are
entirely from the literature. If the trait Word doc does not explain why
the traits differ (and I'm not sure why they ever would) we must assume
that this was an error in input. For the Limoniidae everything but body
size should be consistent. You're next challenge is to figure out which is
the best trait value - here ask yourself whcih trait value was most often
given AND which trait value is supported by the notes in the trait doc.

-- 
Diane Srivastava
Professor
Dept of Zoology & Biodiversity Research Centre,
University of British Columbia
6270 University Blvd
Vancouver BC Canada V6T 1Z4
604-822-1350 (no voicemail)

**Comment by adletaw** [comment]
Thanks!  That is EXTREMELY helpful!

On 15-07-15 08:35 PM, Diane Srivastava wrote:
> body size is generally from field observations, the other traits are
> entirely from the literature. If the trait Word doc does not explain why
> the traits differ (and I'm not sure why they ever would) we must assume
> that this was an error in input. For the Limoniidae everything but body
> size should be consistent. You're next challenge is to figure out which is
> the best trait value - here ask yourself whcih trait value was most often
> given AND which trait value is supported by the notes in the trait doc.
>
> -- 
> Diane Srivastava
> Professor
> Dept of Zoology & Biodiversity Research Centre,
> University of British Columbia
> 6270 University Blvd
> Vancouver BC Canada V6T 1Z4
> 604-822-1350 (no voicemail)
>
>
> > @dsrivast Do you have an idea about what to do with species that
> have only
> > been identified to family or subfamily level but have mismatched traits?
> > Should the traits all match? Or may these traits have been observed in
> > the field even if the morphospecies is not further identified?
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> >
> https://github.com/SrivastavaLab/bwg_names/issues/37#issuecomment-121793133
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SrivastavaLab/bwg_names/issues/37#issuecomment-121817515>.
>

-- 
Alathea D. L.
PhD Candidate, Srivastava Lab
www.zoology.ubc.ca/~srivast

**Comment by adletaw** [comment]
completed with [merge](https://github.com/SrivastavaLab/bwg_names/commit/40556789f5cd456bf6570e58ec9e2cb8b05a8401)
