### ISSUE TITLE
Check decimal values on Tachet traits

### ISSUE THREAD

**Issue by adletaw** [SrivastavaLab/bwg_names#45]
Some traits have decimal values but they should all be integers.

**Comment by angienic** [comment]
Ah we're free to round up then. Thanks!

**Comment by dsrivast** [comment]
Hi Angie-
Which groups of organisms are you working on? I will provide integer values for chironomids and ceratopogonids as I need to take the mode of multiple genera.

**Comment by angienic** [comment]
Hey Diane,
Saulo and I are working on Syrphidae_et_al, there are also a few Ceratopogonids there. 
We are on K582-K598. Would you like us to take the mode or would you rather we leave it to to you?

**Comment by dsrivast** [comment]
Syrphids - please calculate modal traits yourself, take the modal average over all records within the finest taxonomic scale of identification. E.g. if just identified as Syrphidae (family-level), take the modal average of every genus within Syrphidae represented in the BWG database. For the Ceratopogonidae, I have done this for you - am emailing file directly.

**Comment by saulojacques** [comment]
Hi, Diane
Thanks!
