### ISSUE TITLE
Check 4 ceratopogonids with decimal figures not highlighted

### ISSUE THREAD

**Issue by angienic** [SrivastavaLab/bwg_names#53]
Just in case our comment in the text file gets missed, note there are 4 rows of Ceratopogonids (k140, k142, k131 and k165) that are not highlighted in Kathleen and Sadies' spreadsheet as needing review but they probably do as they have decimal figures in several columns. Worth a check!

**Comment by aammd** [comment]
I think this is done! right, @angienic ?

**Comment by angienic** [comment]
yeap, all good @aammd. Thanks!
