### ISSUE TITLE
Chironomid issues 

### ISSUE THREAD

**Issue by aammd** [SrivastavaLab/bwg_names#55]
from @dsrivast 's comment on 6583a9a

- [x] All non-integer values of traits pooled over higher taxonomic orders to be replaced with integer modal values.
- [x] Let us change, for every chironomid species: RF1=1, RF2=0, RF3=1, RF4=2. This deviates slightly from Tachet's 0,0,0,3 coding for all chironomids, but I have found enough examples (documented in DS notes) of resistant eggs (RF1) and diapause (RF3) to cast doubt on no resistance forms (RF4) being universal.
- [x] K186, K187: Although this is a Polypedilum, it has just NAs. We can match the traits from, for example, K196, another Polypedilum.
- [x] K192 (Diptera 447) is a "black-headed chironomid" which is likely a Sciaridae. After we pull Alathea's commits, we can copy every column except Name and Nickname from k238 to K192.
- [x] K273, K203, K204, K205, K220: All Tanytarsus. Need to make RE traits consistent. RE2->1, RE4->3, RE5->0 reason: "Majority of Tanytarsus species have egg strings, a few reports of single eggs. Tanytarsus (various species): Eggs on a gelatinous mass on suspensory stalk" (DS notes).
- [x]  K221. Need to make this Limnophyes sp consistent with congener K183. RF1 0.33->1, RF3 0.67->1, LO5 1.33->1, LO6 0.33->1, LO7->1, FD1 2.67->3, FD6 0.33->0, FG1 1.33->2, FG2 0.67->2, FG3 1.33->2, FG4 2.67->2 will do it.

**Comment by aammd** [comment]
There were over 400 changes, so i used an R script to create the new data. Is this way of doing it OK, @dsrivast ? it makes the list of changes rather long :sweat_smile:

**Comment by dsrivast** [comment]
Yikes, 400 changes! Certainly automating it in R sounds sensible. In terms of the diffs: I think this is one case where I'm just going to have to trust that your R code did everything right - you probably spot checked a few, right?

**Comment by aammd** [comment]
measure twice, cut once :straight_ruler: :straight_ruler: :hocho: 
I checked the [data diff](http://htmlpreview.github.io/?https://raw.githubusercontent.com/SrivastavaLab/bwg_names/comparisons-diane/data/comparisions/01_chironomidae.html) and found that the numbers moved very little (as one would hope, going from the mean to the mode)
I broke the data down into three groups:
* Tanypodine chironomids: no changes needed
* nonTanypodine chironomids (IDed to subfamily): replaced with "detritivorous chironomids". only one such taxa, [Limnophyes](https://github.com/SrivastavaLab/bwg_names/blob/9130a433aaa28a24ead8ffd1656d5d4d24137bd8/data/tachet_01_chironomidae.tsv#L33) (NOTE that is a link to a specific commit!)
* Chironomids not IDed to subfamily: these got the "all chironomids" modal values.

\*Note that, as described above, those values for Lymnophyes (k221) have to change again.

**Comment by aammd** [comment]
k186 and k187 were corrected in 9130a43 above: they have a generalized chironomid trait configuration.
In 6e30138 i confirmed that they are identical to k196
