### ISSUE TITLE
Fixing a few remaining NA traits!

### ISSUE THREAD

**Issue by aammd** [SrivastavaLab/bwg_names#56]
If we want to change this matrix at this point, should we do so here or in the database? @adletaw , cc @dsrivast ?

There is an NA for Oligochaeta.8 , modality LO7. It is NA, should be 0

**Comment by aammd** [comment]
Also in Ostracoda.2 AND Ostracoda.7 same modality

**Comment by adletaw** [comment]
In database I guess.  What did you decide?  I have changed something in 
the database already...we should keep track of these changes though.

On 9/17/2015 10:03 AM, Andrew MacDonald wrote:
>
> Also in Ostracoda.2 AND Ostracoda.7 same modality
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SrivastavaLab/bwg_names/issues/56#issuecomment-141150785>.
>

-- 
Alathea D. L.
PhD Candidate, Srivastava Lab
www.zoology.ubc.ca/~srivast

**Comment by aammd** [comment]
changed already in dc65a5d ; we must do the same in the DB soon or one day will will try to get those data and will be confused

**Comment by adletaw** [comment]
@aammd Please continue to make all changes in this repository until 
after the BWG database workshop.  We may have to repopulate the database 
again depending on how that workshop goes.

On 9/17/2015 9:59 AM, Andrew MacDonald wrote:
>
> If we want to change this matrix at this point, should we do so here 
> or in the database? @adletaw <https://github.com/adletaw> , cc 
> @dsrivast <https://github.com/dsrivast> ?
>
> There is an NA for Oligochaeta.8 , modality LO7. It is NA, should be 0
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SrivastavaLab/bwg_names/issues/56>.
>

-- 
Alathea D. L.
PhD Candidate, Srivastava Lab
www.zoology.ubc.ca/~srivast

**Comment by dsrivast** [comment]
@aamd lets try to keep all updates synchronous between bwg_names on github
and BWGdb for now. If this gets out of hand, we need to then quickly
address how to directly accessing SQL data from BWGdb via R. But for now
its just a few fixes and we can manage it.....


-- 
Diane Srivastava
Professor
Dept of Zoology & Biodiversity Research Centre,
University of British Columbia
6270 University Blvd
Vancouver BC Canada V6T 1Z4
604-822-1350 (no voicemail)
