### ISSUE TITLE
Added diffs for comparing data files

### ISSUE THREAD

**Issue by adletaw** [SrivastavaLab/bwg_names#62]
Hello @aammd @dsrivast ,

I created some diffs to show the differences between our data file versions.  They are in the folder [diffs](https://github.com/SrivastavaLab/bwg_names/tree/master/diffs) (Andrew, did you do this already?  I thought you had, but couldn't find them).

To view them, you can either pull the files to your local repository and open them, or click the links below to render them:

[9 and 10](https://htmlpreview.github.io/?https://github.com/SrivastavaLab/bwg_names/blob/master/diffs/diff-09-10.html)
[10 and 11](https://htmlpreview.github.io/?https://github.com/SrivastavaLab/bwg_names/blob/master/diffs/diff-10-11.html)
[11 and 12](https://htmlpreview.github.io/?https://github.com/SrivastavaLab/bwg_names/blob/master/diffs/diff-11-12.html)
[12 and 14](https://htmlpreview.github.io/?https://github.com/SrivastavaLab/bwg_names/blob/master/diffs/diff-12-14.html)
[14 and 15](https://htmlpreview.github.io/?https://github.com/SrivastavaLab/bwg_names/blob/master/diffs/diff-14-15.html)
[15 and 16](https://htmlpreview.github.io/?https://github.com/SrivastavaLab/bwg_names/blob/master/diffs/diff-15-16.html)
[16 and forupload](https://htmlpreview.github.io/?https://github.com/SrivastavaLab/bwg_names/blob/master/diffs/diff-16-forupload.html)

As you can see if you look at [15x16]() and the [final comparison](), we already have errors in the final upload file due to disorganization.  Changes that were made in script 16 are reversed in `forupload`.

Let's avoid more errors by making sure that any changes made before uploading the final data file to the database are added in R scripts and not manually.  To generate the `forupload.csv` file, you must first run [script 99](https://github.com/SrivastavaLab/bwg_names/blob/master/Rscripts/99_final_step_format_for_bwgdb.R) which renames the columns and removes the `key` column.  This script also creates one version with the `key` column retained.

**Comment by adletaw** [comment]
I also created a [master script](https://github.com/SrivastavaLab/bwg_names/blob/master/Rscripts/00_MASTER.R) that will run all of our numbered scripts and generate the `forupload` file automatically.  However, I am afraid to run it because I'm not confident that the new `forupload` will be the same as the old `forupload` even though it should be.

**Comment by adletaw** [comment]
I created a new branch to compare our current data files with the new ones generated by the master script.  (The Master script only runs from 14 on because changes were made manually to the Tachet traits).  You can see those comparisons  here:

[14](https://htmlpreview.github.io/?https://github.com/SrivastavaLab/bwg_names/blob/run-master/diffs/diff_old_new_14.html)
[15](https://htmlpreview.github.io/?https://github.com/SrivastavaLab/bwg_names/blob/run-master/diffs/diff_old_new_15.html)
[16](https://htmlpreview.github.io/?https://github.com/SrivastavaLab/bwg_names/blob/run-master/diffs/diff_old_new_16.html)
[forupload](https://htmlpreview.github.io/?https://github.com/SrivastavaLab/bwg_names/blob/run-master/diffs/diff_old_new_forupload.html)

All good except for number 16.

**Comment by aammd** [comment]
> (The Master script only runs from 14 on because changes were made manually to the Tachet traits)

I feel like that rather defeats the purpose! :disappointed:  
should we abstract those changes to (yet another) file?

**Comment by adletaw** [comment]
It had to be that way.  Script 13 splits the data into Tachet files.  If you run that it will overwrite the changes that were made.  I don't know what we should do - it is a mess.

**Comment by aammd** [comment]
I don't want to come on too strong here, but if we can't make our changes reproducible then I think we are in trouble.

**Comment by adletaw** [comment]
We lost that privilege when we started editing CSVs by hand.

**Comment by adletaw** [comment]
There is no way to commute any changes to scripts 1-12 into data from 14 on because step 13 was all done by hand.

**Comment by adletaw** [comment]
Yes, if we could convert those edits to the trait subsets into R scripts, basically in the style of what Diane is doing [in 17](https://github.com/SrivastavaLab/bwg_names/blob/master/Rscripts/17_add_missing_traits.R), then I think we would be OK.  I'm still not sure this gets us from the original `Distribution_organisms` file to what we have now.  I think some other things were changed by hand sometime else.

**Comment by adletaw** [comment]
We can also add the notes everyone made to go with those edits - into the new subscripts.

**Comment by aammd** [comment]
Could not the work that Diane was doing in [17](https://github.com/SrivastavaLab/bwg_names/blob/5f182914983011e45c0d5041870c485e10977ea5/Rscripts/17_add_missing_traits.R) be done with a lookup table?

**Comment by adletaw** [comment]
Yes, probably.

**Comment by dsrivast** [comment]
I'm not sure which is worse, discovering that I could have replaced 30 lines of code with a look up table or finding that information on a site called R for dummies.
