### ISSUE TITLE
Taxonomy

### ISSUE THREAD

**Issue by adletaw** [SrivastavaLab/bwg_names#8]
- [x] Fill in missing data
- [x] Correct spelling
- [ ] Address any unresolved issues in [Vinicius' file](https://github.com/SrivastavaLab/bwg_names/blob/master/taxonimical%20problems)

[Data here](https://github.com/SrivastavaLab/bwg_names/blob/master/data/taxonomic.tsv)

**Comment by aammd** [comment]
OK @farjalla this should be ready to go now! FYI here is a handy [tutorial about taxize](http://ropensci.org/tutorials/taxize_tutorial.html)!

**Comment by farjalla** [comment]
Questions in the taxonomic issue:
1. May I create a new column in the file? "Lower taxonomic classification" of some groups is wrong (ex. Copepoda is a subclass and our first column refers to order);
2. What should I put in open cells? There are two kinds of them: first where there is no intermediate classification (ex. there is no sub-family in the Scirtidae family) or second where the lower tanoxomic classification was not achieved.

**Comment by farjalla** [comment]
One more question;
In some cases there is the species name as Cecidomyiidae sp. 2 but the lowest taxonomic level know is family (Cecidomyiidae). How should I proceed? May I delete the name Cecidomyiidae sp. 2 as it is meaningless in relation to taxonomy or keep it? In the second case, how should I deal with the "open cells" of sub-family and genus?

**Comment by farjalla** [comment]
I will remove lines 678-679-670 (keys 677, 678, 679). They are just part of organisms.

**Comment by adletaw** [comment]
Do you mean these?

https://github.com/SrivastavaLab/bwg_names/blob/master/data/taxonomic.tsv#L678-L680

Don't we still need to retain these even though there is no taxonomic information?  Otherwise we will not be able to put the relevant abundances into the database.

**Comment by farjalla** [comment]
ok. I will keep

**Comment by adletaw** [comment]
Should we add more levels of taxonomic detail?  i.e. Domain, Kingdom, Phylum, Class.  I am wondering because we may in the future add in some bacteria or fungi into our survey data and it would help to have those levels, to distinguish them.

**Comment by farjalla** [comment]
I guess we HAVE TO. Some organisms were just have the Class or Sub-Class (ex. Acari, Copepoda, Oligochaetas).
May I do it in my Table? I have almost finished my issue.

**Comment by adletaw** [comment]
Yes, that is fine with me.  I think you are the only one using the table, so it shouldn't mess anyone up.  Maybe you can add the empty new columns and then make the commit.  Then each time you fill in rows for the new columns, those will show up in future commits.

**Comment by adletaw** [comment]
We should make a standard decision about what to put in empty cells.  I think <code>NA</code> is best since that is also the default for missing values in R.

**Comment by adletaw** [comment]
And in response to your question above, it is okay to add more columns for taxonomic divisions.  I would just add all of the new columns first, then commit, then fill in the information.  That will make it easier to track your changes.

**Comment by farjalla** [comment]
I will put NA. Then we can decide further.

**Comment by farjalla** [comment]
I will add the new columns in the Table I am working on. However, I updated this table with the information I collected this morning (i.e. almost all my issue!).

**Comment by farjalla** [comment]
@adletaw I have committed my table. Take a look and see if it is fine. My next step will be adding the new columns and the NAs

**Comment by adletaw** [comment]
Hm, did you push the changes to GitHub?

**Comment by farjalla** [comment]
ops...

**Comment by farjalla** [comment]
done

**Comment by adletaw** [comment]
It looks great!!!!

**Comment by farjalla** [comment]
Pushed the table with 4 new columns (Phyllum, Sub.Phyllum, Class, Sub-Class). It will solve some of our problems.

**Comment by adletaw** [comment]
Looking very good!

**Comment by farjalla** [comment]
O notice a problem in a nickname (L78)
https://github.com/SrivastavaLab/bwg_names/blob/master/data/taxonomic.tsv#L78
The organism is a Copepoda, not a Coleoptera.

**Comment by adletaw** [comment]
Okay.  We may have some problems with nicknames, including some that are missing.  Andrew will create a separate issue for this and we can fix them up after your work on taxonomy is done.

**Comment by farjalla** [comment]
ok. Lets just keep it in mind

**Comment by farjalla** [comment]
I add a "readme" file with the problems I reported so far and I could not solve (2 problems until ~L380).

**Comment by adletaw** [comment]
Good idea!  I am adding a [link to your file here](https://github.com/SrivastavaLab/bwg_names/blob/master/taxonimical%20problems).
