### ISSUE TITLE
Label aquatic/terrestrial

### ISSUE THREAD

**Issue by adletaw** [SrivastavaLab/bwg_names#9]
- [ ] Set aquatic, semiaquatic, terrestrial labels for all known species.
- [ ] Create a list of unresolved species
- [ ] Send to BWG for resolution
- [x] Add NA for any species that cannot be labeled

[Data here](https://github.com/SrivastavaLab/bwg_names/blob/master/data/aquatic_terrestrial_only.tsv)

**Comment by nacmarino** [comment]
hey @adletaw...whatever I modify one cell from the data file and try to commit it, it tell me I deleted the entire row and made a new one...is that correct?

**Comment by adletaw** [comment]
Yep!  That is how it is supposed to go.

**Comment by adletaw** [comment]
Push some changes so we can see what you are doing!

**Comment by nacmarino** [comment]
Pushed the table, put still have some questions about classification.

**Comment by adletaw** [comment]
Okay, I see what you did.  It looks like you had to merge the taxonomic.tsv file as well.  In the future if you pull new changes right before pushing your own changes, you should not have this merge problem.  Did you get any error messages when you pushed?

**Comment by adletaw** [comment]
What are your classification questions?

**Comment by aammd** [comment]
OK so unfortunately the original data file that Nicolas worked on was far too large. I've added a new file in 8f17e4d42c9158a4e97f4872e94739cf62bdfe71 for Nicolas to put his data in

**Comment by nacmarino** [comment]
Now it's okay.

The classification is just that the taxonomy in such a high level, that I
can't be sure that the organism is in fact aquatic. For Macae I can tell
that, but not for other sites...

**Comment by aammd** [comment]
I Feel like that would be an NA? @dsrivast , what do you think?

**Comment by adletaw** [comment]
We may be able to compile a list and ask the rest of the BWG if they can solve any of those unknowns.  Otherwise, NA is basically the only choice.  Can @DEZERALDOlivier help with any of the French Guiana organisms?

**Comment by DEZERALDOlivier** [comment]
I'll look at it but I'll wait to be alone working on the file, don't want to make mistakes again!

**Comment by nacmarino** [comment]
You can go on, I won't work on it now! hahaha

**Comment by nacmarino** [comment]
Where can I create a list for the unresolved species, @adletaw?

**Comment by aammd** [comment]
By unresolved species, @nacmarino , do you mean species that aren't identified, or species that don't have a value for aquatic or terrestrial (ie are NA)

**Comment by nacmarino** [comment]
I mean species we are not sure on their habitat, such as those marked as
a/sa or sa/t. Or even species that are marked as aquatic, but I couldn't
find any references for aquatic larvae of that particular genus/family.

**Comment by nacmarino** [comment]
@aammd and @adletaw, I was talking with @farjalla and he said his table has now a better taxonomic resolution than mine. Could you create a new data file, containing the column I already worked on, with the information from @farjalla table? I think we can advance with the aquatic/terrestrial pretty much this way!

**Comment by farjalla** [comment]
The point is the information in the "name" column might be incomplete. For instance, some name columns are codes and the whole information about the species appears in other columns. I would prepare a new table with all the taxonomic information to other characterization.

**Comment by adletaw** [comment]
if you want, you can make a new file with the list and push it to the 
repository

On 03/13/2015 02:08 PM, Nicholas Marino wrote:
> I mean species we are not sure on their habitat, such as those marked as
> a/sa or sa/t. Or even species that are marked as aquatic, but I couldn't
> find any references for aquatic larvae of that particular genus/family.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SrivastavaLab/bwg_names/issues/9#issuecomment-79400303>.
>

-- 
Alathea D. L.
PhD Candidate, Srivastava Lab
www.zoology.ubc.ca/~srivast

**Comment by adletaw** [comment]
@nacmarino Vinicius added some columns to the [taxonomic data](https://github.com/SrivastavaLab/bwg_names/blob/master/data/taxonomic.tsv).  Perhaps you can reference that table while you are going through yours?  It is easier if we join all of the tables once they are all done.

**Comment by dsrivast** [comment]
Hi crew-
Sorry I missed jumping in earlier. If you are unsure about anything about a species - e.g. whether it is aquatic or terrestrial - can I suggest that the first thing you should do is to contact the researcher, who probably knows the answer. If THEY do not know the answer, only then put "NA". Once this data is in the database, it will take a Herculean effort to improve it (realistically, this will never happen), so we should try to make it the best possible quality data at this stage please. best Diane

**Comment by nacmarino** [comment]
Working on that now, then.

**Comment by nacmarino** [comment]
Okay.

So, I created a new data table (aquatic_terrestrial_unknowns) with all
species I'm not certain. I'll send an email for the person responsible for
the dataset in each country. However, I need to confirm whom should I
contact, for:

AR (Argentina) - Ignacio (?)
Brazil Cardoso - Gustavo Romero (?)
CO (Colombia?) -
DO (Dominica?) - Barbara Richardson (?)
HO (Honduras?) -
JP (???) -
PR (Puerto Rico) - Barbara Richardson (?)
SA (Saba) - Barbara Richardson (?)

Also, could you provide me the e-mails for those people?

**Comment by adletaw** [comment]
The Colombia data comes from Fabiola.  You can find all of the email 
addresses on the BWG website here:

http://www.zoology.ubc.ca/~srivast/bwg/researchers.html

On 3/16/2015 11:36 AM, Nicholas Marino wrote:
> Okay.
>
> So, I created a new data table (aquatic_terrestrial_unknowns) with all
> species I'm not certain. I'll send an email for the person responsible for
> the dataset in each country. However, I need to confirm whom should I
> contact, for:
>
> AR (Argentina) - Ignacio (?)
> Brazil Cardoso - Gustavo Romero (?)
> CO (Colombia?) -
> DO (Dominica?) - Barbara Richardson (?)
> HO (Honduras?) -
> JP (???) -
> PR (Puerto Rico) - Barbara Richardson (?)
> SA (Saba) - Barbara Richardson (?)
>
> Also, could you provide me the e-mails for those people?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SrivastavaLab/bwg_names/issues/9#issuecomment-81858907>.
>

-- 
Alathea D. L.
PhD Candidate, Srivastava Lab
www.zoology.ubc.ca/~srivast

**Comment by nacmarino** [comment]
Does anyone has Merlijn Jocque e-mail?

**Comment by farjalla** [comment]
merlijnjocque@gmail.com

Vinicius F Farjalla, Dr.,
Professor Adjunto
Associate Professor
http://www.researcherid.com/rid/G-4945-2010

Depto. Ecologia,  Inst. Biologia, Universidade Federal do Rio de
Janeiro, Rio de Janeiro, RJ, 21941-590, Brazil.
Phone: +55 21 2562 6374

2015-03-17 16:34 GMT-07:00 Nicholas Marino <notifications@github.com>:

**Comment by adletaw** [comment]
@nacmarino How is this going?

**Comment by nacmarino** [comment]
Just need info from Gustavo Romero and the Richardsons. All else good to go.

**Comment by adletaw** [comment]
Sounds good!  I may be able to help on some of the Cardoso data.  I'll take a look.

**Comment by nacmarino** [comment]
There is a file, aquatic_terrestrial_unknowns.txt, on the main folder. All
the unresolved unknowns are there.

2015-04-02 11:28 GMT-07:00 Alathea <notifications@github.com>:

> Sounds good! I may be able to help on some of the Cardoso data. I'll take
> a look.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SrivastavaLab/bwg_names/issues/9#issuecomment-89001671>
> .
>



-- 
Nicholas Marino, MSc.
Universidade Federal do Rio de Janeiro
Laboratório de Limnologia
Site: www.biologia.ufrj.br/limnologia/
Blog: www.limnonews.wordpress.com

**Comment by aammd** [comment]
@nacmarino  is this complete now? I guess we are still waiting for some information. But if we are switching to working on the full data then i guess we can close this?
